#!/bin/sh
set -e

case "$1" in
    configure)
    /usr/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
    /usr/bin/gtk4-update-icon-cache -q -t -f /usr/local/share/icons/hicolor
    /usr/bin/update-desktop-database -q /usr/local/share/applications
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
